server:
  port: 8092

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
  
spring:
  application: #micros register name
    name: microservicecloud-business-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/microcloud002       
    username: root
    password: admin
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

 
eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      #http://localhost:7001/eureka
  instance:
     instance-id: micros-business-dept-8092
     prefer-ip-address: true
     
     
info:
  app.name: xfang-microservicecloud-business
  company.name: www.xfang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
