server:
  port: 8090

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
  
spring:
  application:
    name: microservicecloud-business
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/microcloud001       
    username: root
    password: admin
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

 